# -*- coding: utf-8 -*-
"""Power_Factor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLkgWYiUHqpaZkU9q4V7UNJtuDa-txiL
"""

import boto3
import json
import time
from random import uniform
from datetime import datetime

cliente = boto3.client(
    'kinesis',
    aws_access_key_id='<<id_do_usuario>>',
    aws_secret_access_key='<<chave>>>',
    region_name='<<Regiao>>'
)

id = 0
while True:
  dados = uniform(0.7,1)
  id += 1;
  registro = {
      'idtemp': str(id),
      'data': str(dados),
      'type': 'powerfactor',
      'timestamp': str(datetime.now())
      }

  cliente.put_record(
      StreamName='windfarm',
      Data = json.dumps(registro),
      PartitionKey='02'
      )
  print(registro)

  time.sleep(10)

